### ISSUE TITLE
levels are not selecting

### ISSUE THREAD

**Issue by grawish** [untitled-team-101/2048#1]
# Levels are not selecting
- Open the Website
- Click next
- select levels
- Levels are not opening
![Screenshot from 2021-10-05 10-35-38](https://user-images.githubusercontent.com/41504211/135963378-e78071de-1ec3-4b11-b98e-cffcab93d47e.png)

**Comment by ayan-dhara** [comment]
@grawish May I assign this to myself ?

**Comment by grawish** [comment]
Yes ofcourse 😙

**Comment by grawish** [comment]
Thank You @Ayan-Dhara for Solving this Issue
